apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: odoo
  name: odoo
spec:
  ports:
  - name: 8069-8069
    port: 8069
    protocol: TCP
    targetPort: 8069
  - name: 8072-8072
    port: 8072
    protocol: TCP
    targetPort: 8072
  selector:
    app: odoo
  type: ClusterIP
status:
  loadBalancer: {}
